# Generated by Django 4.2.3 on 2025-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hack',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
