# Generated by Django 4.2.3 on 2025-03-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('hacks', '0002_alter_hack_content_alter_hack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
