# Generated by Django 4.2.3 on 2025-03-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('hacks', '0004_remove_hack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category'),
        ),
    ]
